name: Update ReadMe

on:
  push:
    branches:
      - hikari-x86_64

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: rlespinasse/git-commit-data-action@v1.x

      - name: Generate README.md
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          export README_md="$(<./.github/README.md.tpl)"
          export COMMIT_ms="$(sed 1q <<< "${{ env.GIT_COMMIT_MESSAGE_BODY }}")"
          if [[ "$COMMIT_ms" = *'x86_64'* ]]; then
             sed "s|_KVER_|${COMMIT_ms}|g" > ./README.md <<< "$README_md"
          elif [[ "${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}" = *'README.md.tpl'* ]]; then
             export KVER_sign="$(grep -m1 -oP '# .*>`\K[^`</p>]+' ./README.md)"
             sed "s|_KVER_|${KVER_sign}|g" > ./README.md <<< "$README_md"
          fi

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: '🡲 Sync README.md'
          commit_user_name: '光'
          commit_user_email: 'alternate-se7en@pm.me'
          commit_author: '光 <alternate-se7en@pm.me>'
          add_options: '-u'
          push_options: '--force'
          skip_dirty_check: true
          disable_globbing: true
